model:
  base_learning_rate: 4.5e-6
  target: cheff.ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: cheff.ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 5001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  params:
    batch_size: 8
    machex_path: /machex
    test_size: 25000
    num_workers: 16

lightning:
  callbacks:
    image_logger:
      target: scripts.01_train_ldm.ImageLogger
      params:
        batch_frequency: 2500
        max_images: 8
        increase_log_steps: True

  trainer:
    gpus: 8
    benchmark: False
    precision: 32
